<?php
/**
*Index.php is used as a bootstrap for the application
*
*Start session
*Require the PS4 autoload generated by composer
*Instantiate the router with URI request
*Catching differents exceptions
*/
session_start();
require_once __DIR__ . '/vendor/autoload.php';

use Blog\Controller\Router\Router;

try
{
	new Router($_SERVER['REQUEST_URI']);
}

//exceptions management
catch (PDOException $e)
{
	  echo 'La connexion a échoué.<br />';
	  echo 'Informations : [', $e->getCode(), '] ', $e->getMessage(); 
}

catch (Twig_Error $e)
{
	echo 'Erreur Twig :' . $e->getMessage();
}

catch(Exception $e)
{
    echo 'Erreur : ' . $e->getMessage();
}